# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
matrix:
  fast_finish: true
  allow_failures:
  - julia: nightly

notifications:
  email: true

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';

codecov: true

#after_success:
   #- julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);' 
